### ISSUE TITLE
unsupported Compose file version: 2.3

### ISSUE THREAD

**Issue by patrickng** [docker/aci-integration-beta#13]
Attempting to run `docker compose up`, getting an error returned "unsupported Compose file version: 2.3"

System info:

```
➜ docker version
Client: Docker Engine - Community
 Azure integration  0.1.4
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

➜ docker-compose --version
docker-compose version 1.26.0, build d4451659
```

What is the minimum docker compose file version that's supported in this ACI context?

**Comment by chris-crone** [comment]
Hi @patrickng!

Sorry for the late reply. We currently support version 3 of the Compose file format but in the near future we will support v2 as well.

The Compose specification has [dropped the requirement for the version field in the Compose file](https://github.com/compose-spec/compose-spec/pull/82) so we will do the same for the ACI integration.

**Comment by gtardif** [comment]
This has been fixed now, you can run without a version number in your compose file, or v2 or v3 version numbers
