### ISSUE TITLE
Docker Login Azure issues

### ISSUE THREAD

**Issue by NickKarsky** [docker/aci-integration-beta#15]
When running 'docker login azure' on a VM in azure, it asks for a username and pass from stdin instead of opening the browser to login. Any ideas why this might be happening and how to fix it? Its a windows 10 VM with docker for desktop installed.

**Comment by xbringer** [comment]
I had the same problem. It's probably running Docker Desktop stable and not the newest Edge release you need.

**Comment by gtardif** [comment]
Indeed, it seems you are not running the latest edge version, and the CLI does not include the azure integration. 
You can check `docker version`, it should display the version of the azure integration if it is available:
```
 $ docker version 
Client: Docker Engine - Community
 Azure integration  0.1.5
 Version:           19.03.12
 API version:       1.40
... 
```

**Comment by gtardif** [comment]
Closing this one, since it seems to be an install issue.
