### ISSUE TITLE
Add the ability to connect Azure file shares via Docker Compose

### ISSUE THREAD

**Issue by Kibnet** [docker/aci-integration-beta#30]
You can already connect Azure file resources as volumes via flag "-v" by "docker run". Similarly, you want to do this in Docker Compose.

**Comment by gtardif** [comment]
This actually needed documentation, it is already supported in compose as well. 
Added the information in our docs repo: https://github.com/docker/docker.github.io/pull/11314

**Comment by gtardif** [comment]
This has been documented, and basic volume management commands for Azure fileshares have been added as well. See https://docs.docker.com/engine/context/aci-integration/
